apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uptime-kuma-reconciler.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma-reconciler.labels" . | nindent 4 }}
data:
  KUMA_URL: {{ .Values.kumaUrl | quote }}
  RESYNC_INTERVAL: {{ .Values.resyncInterval | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  MONITOR_NAME_INCLUDE_NAMESPACE: {{ .Values.monitorNameIncludeNamespace | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uptime-kuma-reconciler.fullname" . }}-script
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma-reconciler.labels" . | nindent 4 }}
data:
  reconciler.py: |
{{ .Files.Get "files/reconciler.py" | indent 4 }}
  requirements.txt: |
{{ .Files.Get "files/requirements.txt" | indent 4 }}
